# Generated by Django 3.2.5 on 2021-08-10 00:35

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='UserInfo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=30)),
                ('last_name', models.CharField(max_length=30)),
                ('email', models.EmailField(max_length=128)),
                ('qualification', models.CharField(choices=[('UG', 'UnderGraduate'), ('G', 'Graduate'), ('PG', 'PostGraduate'), ('PhD', 'Doctor of Philosophy')], max_length=10)),
            ],
        ),
    ]
