# Generated by Django 3.2.5 on 2021-08-08 09:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('AppTwo', '0002_auto_20210731_1127'),
    ]

    operations = [
        migrations.AddField(
            model_name='usersinfo',
            name='qualification',
            field=models.CharField(choices=[('UG', 'Under Graduate'), ('G', 'Graduate'), ('PG', 'Post Graduate'), ('PhD', 'Doctor of Philosophy')], default=None, max_length=10),
        ),
        migrations.AlterField(
            model_name='usersinfo',
            name='email',
            field=models.EmailField(max_length=128, unique=True),
        ),
        migrations.AlterField(
            model_name='usersinfo',
            name='first_name',
            field=models.CharField(max_length=30),
        ),
        migrations.AlterField(
            model_name='usersinfo',
            name='last_name',
            field=models.CharField(max_length=30),
        ),
    ]
