# Generated by Django 3.2.5 on 2021-08-21 23:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('school_basic', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='schoolinfo',
            name='zip',
            field=models.PositiveIntegerField(),
        ),
    ]
