# Generated by Django 3.2.5 on 2021-08-22 09:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('school_basic', '0003_alter_schoolinfo_contact_number'),
    ]

    operations = [
        migrations.AlterField(
            model_name='schoolinfo',
            name='contact_number',
            field=models.CharField(max_length=20),
        ),
    ]
