# Generated by Django 3.2.5 on 2021-09-01 00:26

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comment',
            name='create_data',
            field=models.DateTimeField(default=datetime.datetime(2021, 9, 1, 0, 26, 19, 216260, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='post',
            name='create_data',
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='userinfo',
            name='gender',
            field=models.CharField(choices=[('M', 'Male'), ('F', 'Female')], default='null', max_length=3),
        ),
    ]
