# Generated by Django 3.2.5 on 2021-09-01 06:03

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0003_alter_comment_create_data'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comment',
            name='create_data',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
