# Generated by Django 3.2.5 on 2021-09-01 09:50

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('blog', '0004_alter_comment_create_data'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='author',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='blog.userinfo', verbose_name='related to blog Author'),
        ),
        migrations.AlterField(
            model_name='post',
            name='create_data',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AlterField(
            model_name='post',
            name='designation',
            field=models.CharField(choices=[('VP', 'Vice President'), ('MN', 'Manager'), ('TM', 'Team Lead'), ('CIO', 'Chief Information Officer')], default='VP', max_length=30),
        ),
        migrations.AlterField(
            model_name='userinfo',
            name='date_of_birth',
            field=models.DateField(help_text='Please use the following format:<em>dd/mm/yyyy</em>'),
        ),
        migrations.AlterField(
            model_name='userinfo',
            name='user',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Author of blog'),
        ),
    ]
