# Generated by Django 3.2.5 on 2021-09-24 00:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0005_auto_20210901_1950'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='designation',
            field=models.CharField(choices=[('Vice President', 'VP'), ('Manager', 'MN'), ('Team Lead', 'TM'), ('Chief Information Officer', 'CIO')], default='VP', max_length=30),
        ),
    ]
