# Generated by Django 3.2.5 on 2021-09-24 01:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0006_alter_post_designation'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='designation',
            field=models.CharField(choices=[('VICE PRESIDENT', 'Vice President'), ('MANAGER', 'Manager'), ('TEAM LEAD', 'Team Lead'), ('CHIEF INFORMATION OFFICER', 'Chief Information Officer')], default='VICE PRESIDENT', max_length=30),
        ),
        migrations.AlterField(
            model_name='userinfo',
            name='gender',
            field=models.CharField(choices=[('MALE', 'Male'), ('FEMALE', 'Female')], default='null', max_length=10),
        ),
    ]
